name: Loop Structure
type: birkeland
animations:
  particles:
    speed: .1

#timers:
# loop:
#   - {time: 2000, steps: 40, parms: {attachLines--scale: [1,2.25]}}
#   - {time: 3000, steps: 1}
#   - {time: 2000, steps: 40, parms: {proton--scale: [1,.25]}}
#   - {time: 3000, steps: 1}
#   - {time: 2000, steps: 40, parms: {attachLines--scale: [2.25,1]}}
#   - {time: 3000, steps: 1}
#   - {time: 2000, steps: 40, parms: {proton--scale: [.25,1]}}
#   - {time: 3000, steps: 1}
