name: Birkeland Builder
defaultView: default
themeDirectory: config/themes/birkeland
animateDirectory: config/animations/birkeland
controlFile: controls_birkeland.yml
atomizerId: birkeland
classes: [az-float-controls]
libraries: [atomizer/atomizer-obfuscator, atomizer/atomizer-birkeland-obfuscator]
librariesDev: [atomizer/atomizer-base, atomizer/atomizer-birkeland]
objects: [nuclets]
canvasRatio: window
renderer: webgl
startAnimation: true
views:
  default:
    name: Birkeland Current Simulator
    producer: prod_birkeland
    defaultTheme: default
